import Nav from './component/navbar/nav'
import './globals.css'

export const metadata = {
  title: 'Dominion Gospel Ministry',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script src="https://kit.fontawesome.com/d5fed1061e.js" crossorigin="anonymous"></script>
      </head>
      <body>
        <header>
          <Nav />
        </header>
        {children}</body>
    </html>
  )
}
